# config.yaml

server:
  host: localhost
  port: 8080

database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: password

logging:
  level: INFO
  file: /var/log/app.log

features:
  enableFeatureX: true
  enableFeatureY: false